services:
  traefik:
    image: "traefik:v3.6.13"
    container_name: "traefik"
    restart: always
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    ports:
      - "443:443/tcp"
      - "443:443/udp"
      - "444:444/tcp"
      - "444:444/udp"
      - "445:445/tcp"
      - "445:445/udp"
      - "446:446/tcp"
      - "446:446/udp"
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml"
      - "traefik-acme:/etc/traefik/acme"

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    restart: always
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
    depends_on:
      traefik:
        condition: service_started

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: --interval 86400

volumes:
  traefik-acme:
    name: traefik-acme
    external: true
