api:
  insecure: false
  dashboard: true
  debug: true

log:
  level: INFO

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: common

entryPoints:
  web-secure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
    http3: {}
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "fc00::/7"
        - "fe80::/10"

# Requires CF_DNS_API_TOKEN environment variable for Cloudflare
certificatesResolvers:
  letsencrypt:
    acme:

      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

providers:
  file:
    filename: "/etc/traefik/dynamic_conf.yml"
    watch: true
